update getall for order
eeveesharp/innowisePractice pull request #30
Opened 2022-07-13 13:25 UTC by eeveesharp

2022-07-13 14:15 UTC, hromau requested changes

2022-07-13 14:47 UTC, Blackolf931 approved these changes

2022-07-13 14:49 UTC, hromau requested changes

2022-07-13 15:02 UTC, hromau requested changes

2022-07-13 15:02 UTC, hromau commented on Shop/Shop.BLL/Interfaces/IOrderServices.cs
> +        new Task<Order> Get(int id, CancellationToken ct);
what do u mean? there is two different methods with different names. Get and GetAll. where is relations between them?

2022-07-14 08:31 UTC, eeveesharp commented on Shop/Shop.BLL/Interfaces/IOrderServices.cs
> +        new Task<Order> Get(int id, CancellationToken ct);
method Get - it`s get by id

2022-07-14 10:17 UTC, hromau approved these changes

2022-07-14 10:18 UTC, merged