CRUD for product
eeveesharp/innowisePractice pull request #4
Opened 2022-06-30 12:52 UTC by eeveesharp

2022-06-30 15:07 UTC, hromau commented
get rid folder .vs from git

2022-06-30 15:16 UTC, hromau commented
there is a changes from BIN folder. u must have to delete it from Repo and from Git

2022-06-30 16:02 UTC, nantonov commented
Update .gitignore and exclude unnecessary files

2022-06-30 16:07 UTC, nantonov commented
Get rid of DAL and BL projects

2022-06-30 16:11 UTC, nantonov requested changes
Don't overcomplicate it

2022-07-01 02:19 UTC, stas1408123 requested changes

2022-07-01 02:19 UTC, stas1408123 commented on Shop/DAL/Interfaces/IProductServices.cs
> +        public void Remove(int id);
Rename to delete

2022-07-01 02:19 UTC, stas1408123 commented on Shop/DAL/Interfaces/IProductServices.cs
> +        public Product Read(int id);
Rename to GetProductById

2022-07-01 02:19 UTC, stas1408123 commented on Shop/DAL/Interfaces/IProductServices.cs
> +        public void Update(int id, Product product);
You don't need id

2022-07-01 02:19 UTC, stas1408123 commented on Shop/DAL/Entities/Product.cs
> +    public class Product
Rename ProductEntity

2022-07-01 02:19 UTC, stas1408123 commented on Shop/DAL/Implementations/ProductServices.cs
> +    internal class ProductServices : IProductServices
Implement all methods

2022-07-01 02:19 UTC, stas1408123 commented on Shop/Shop/Controllers/ProductController.cs
> +        public IActionResult Update()
You should get input data in this method

2022-07-01 02:19 UTC, stas1408123 commented on Shop/Shop/Controllers/ProductController.cs
> +                product.Price = 1;
Remove

2022-07-01 02:19 UTC, stas1408123 commented on Shop/Shop/Controllers/ProductController.cs
> +        public IActionResult Create()
You should get input data in this method

2022-07-01 02:19 UTC, stas1408123 commented on Shop/Shop/Controllers/ProductController.cs
> +                Product phone = new Product { Name = "Phone", Price = 123, Quantity = 33 };
remove

2022-07-01 02:19 UTC, stas1408123 commented on Shop/Shop/Controllers/ProductController.cs
> +        public IActionResult Delete()
You should get input data in this method

2022-07-01 02:19 UTC, stas1408123 commented on Shop/Shop/Product.cs
> +    public class Product
Rename ProductViewModels
Add this class into folder which is called ViewModels

2022-07-01 07:16 UTC, closed without merging